import type { Holding } from "./types";

export const holdings: Holding[] = [
  {
    id: "hdfc-bank",
    sector: "Financial Sector",
    name: "HDFC Bank",
    symbol: "HDFCBANK",
    purchasePrice: 1490,
    quantity: 50,
  },
  {
    id: "bajaj-finance",
    sector: "Financial Sector",
    name: "Bajaj Finance",
    symbol: "BAJFINANCE",
    purchasePrice: 6466,
    quantity: 15,
  },
  {
    id: "icici-bank",
    sector: "Financial Sector",
    name: "ICICI Bank",
    symbol: "532174",
    purchasePrice: 780,
    quantity: 84,
  },
  {
    id: "bajaj-housing",
    sector: "Financial Sector",
    name: "Bajaj Housing",
    symbol: "544252",
    purchasePrice: 130,
    quantity: 504,
  },
  {
    id: "savani-financials",
    sector: "Financial Sector",
    name: "Savani Financials",
    symbol: "511577",
    purchasePrice: 24,
    quantity: 1080,
  },
  {
    id: "affle-india",
    sector: "Tech Sector",
    name: "Affle India",
    symbol: "AFFLE",
    purchasePrice: 1151,
    quantity: 50,
  },
  {
    id: "lti-mindtree",
    sector: "Tech Sector",
    name: "LTI Mindtree",
    symbol: "LTM",
    purchasePrice: 4775,
    quantity: 16,
  },
  {
    id: "kpit-tech",
    sector: "Tech Sector",
    name: "KPIT Tech",
    symbol: "542651",
    purchasePrice: 672,
    quantity: 61,
  },
  {
    id: "tata-tech",
    sector: "Tech Sector",
    name: "Tata Tech",
    symbol: "544028",
    purchasePrice: 1072,
    quantity: 63,
  },
  {
    id: "bls-e-services",
    sector: "Tech Sector",
    name: "BLS E-Services",
    symbol: "544107",
    purchasePrice: 232,
    quantity: 191,
  },
  {
    id: "tanla",
    sector: "Tech Sector",
    name: "Tanla",
    symbol: "532790",
    purchasePrice: 1134,
    quantity: 45,
  },
  {
    id: "dmart",
    sector: "Consumer",
    name: "Dmart",
    symbol: "DMART",
    purchasePrice: 3777,
    quantity: 27,
  },
  {
    id: "tata-consumer",
    sector: "Consumer",
    name: "Tata Consumer",
    symbol: "532540",
    purchasePrice: 845,
    quantity: 90,
  },
  {
    id: "pidilite",
    sector: "Consumer",
    name: "Pidilite",
    symbol: "500331",
    purchasePrice: 2376,
    quantity: 36,
  },
  {
    id: "tata-power",
    sector: "Power",
    name: "Tata Power",
    symbol: "500400",
    purchasePrice: 224,
    quantity: 225,
  },
  {
    id: "kpi-green",
    sector: "Power",
    name: "KPI Green",
    symbol: "542323",
    purchasePrice: 875,
    quantity: 50,
  },
  {
    id: "suzlon",
    sector: "Power",
    name: "Suzlon",
    symbol: "532667",
    purchasePrice: 44,
    quantity: 450,
  },
  {
    id: "gensol",
    sector: "Power",
    name: "Gensol",
    symbol: "542851",
    purchasePrice: 998,
    quantity: 45,
  },
  {
    id: "hariom-pipes",
    sector: "Pipe Sector",
    name: "Hariom Pipes",
    symbol: "543517",
    purchasePrice: 580,
    quantity: 60,
  },
  {
    id: "astral",
    sector: "Pipe Sector",
    name: "Astral",
    symbol: "ASTRAL",
    purchasePrice: 1517,
    quantity: 56,
  },
  {
    id: "polycab",
    sector: "Pipe Sector",
    name: "Polycab",
    symbol: "542652",
    purchasePrice: 2818,
    quantity: 28,
  },
  {
    id: "clean-science",
    sector: "Others",
    name: "Clean Science",
    symbol: "543318",
    purchasePrice: 1610,
    quantity: 32,
  },
  {
    id: "deepak-nitrite",
    sector: "Others",
    name: "Deepak Nitrite",
    symbol: "506401",
    purchasePrice: 2248,
    quantity: 27,
  },
  {
    id: "fine-organic",
    sector: "Others",
    name: "Fine Organic",
    symbol: "541557",
    purchasePrice: 4284,
    quantity: 16,
  },
  {
    id: "gravita",
    sector: "Others",
    name: "Gravita",
    symbol: "533282",
    purchasePrice: 2037,
    quantity: 8,
  },
  {
    id: "sbi-life",
    sector: "Others",
    name: "SBI Life",
    symbol: "540719",
    purchasePrice: 1197,
    quantity: 49,
  },
];
